# action.yml
name: 'Dynamic env killer'
description: 'Destroys cloudformation stacks that are no longer required'
inputs:
  filename:
    description: 'Name of file'
    required: true
  stack_prefix:
    description: 'Prefix of stack'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
